GET http://localhost:3002/api/blogs HTTP/1.1

###

GET http://localhost:3002/api/blogs/60cf17e0bf984a3022c73309 HTTP/1.1

###

POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvZXlfdHJpYnMiLCJpZCI6IjYwZGMyYTU3NDgzNWY3MzFmZWZlN2MyZCIsImlhdCI6MTYyNTA1ODE1OH0.vk0FOabvBNrk2L4WfYu0XPlKQYUpHdWrU1A4av-ezeI

{
  "title": "Testauth",
  "author": "Testauth",
  "url": "Testauth",
  "likes": 123
}
###

PUT http://localhost:3002/api/blogs/60dc6c3af11bd733b150c17d HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvZXlfdHJpYnMiLCJpZCI6IjYwZGMyYTU3NDgzNWY3MzFmZWZlN2MyZCIsImlhdCI6MTYyNTA1ODE1OH0.vk0FOabvBNrk2L4WfYu0XPlKQYUpHdWrU1A4av-ezeI

{
  "title": "PutTestWithaUTH",
  "author": "PutTestWithaUTH",
  "url": "PutTestWithaUTH",
  "likes": 11
}
###

DELETE http://localhost:3002/api/blogs/60dc71939826533517a0d3f2 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvZXlfdHJpYnMiLCJpZCI6IjYwZGMyYTU3NDgzNWY3MzFmZWZlN2MyZCIsImlhdCI6MTYyNTA1ODE1OH0.vk0FOabvBNrk2L4WfYu0XPlKQYUpHdWrU1A4av-ezeI

###

